import type { Metadata } from "next";
import { Lora } from "next/font/google";
import "../styles/global.scss";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "GALLERY - home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lora.className}>
        <main className="main">{children}</main>
      </body>
    </html>
  );
}
